Branding:
  Name: "My App"
  Description: "My App is a great app"
  LogoPngFile: "myAppLogo.png"
  
DexConfig:
  ClientId: example-app
  ClientSecret: xxxxx
  ClientRedirectURL: http://zzzzz
  DexIssuer: http://yyyyyy

Database:
  SqliteFilename: "sqlite.db"

