---
title: Select products
description: 'See further <a href="https://my.internal.wiki.corp/vendingmaxine/catalog-default"
  target="_blank">documentation in our corporate wiki, in dedicated page detailing
  these products</a> '
type: object
default: {}
properties:
  additional_members_of_AADGroup_DataClients: 
    title: "AAD-Group 'mycollection_DataClients' members"
    type: object
    properties:
      info:
        type: info
        description: 'The ''mycollection_DataClients'' AAD-Group members can access
          data from resources: blob/files from storage accounts, secrets from keyvaults,
          etc'
      elements:
        title: " "
        type: array
        format: tabs
        default: []
        items:
          headerTemplate: "{{ self.alias }}"
          type: object
          format: grid
          properties:
            alias:
              type: string
              title: Internal alias
              description: An internal alias to remember what this object_id corresponds
                to
              default: 'Exs: ''group TeamWhisky'' or ''user Siegi'' or ''spn cicdWhisky1'''
            object_id:
              type: string
              title: Object_id
              description: Indicate object_id of user, group or spn
              pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
              default: 'Ex: 88888888-4444-4444-4444-121212121212'
  storageaccounts:
    title: StorageAccounts
    type: object
    properties:
      info:
        type: info
        description: 'Azure storageaccounts provide blobs, file-shares and other storage
          services. </br>The first storageaccount is special: must always exist and
          have name storageaccountname = collectionname-without-any-dashes (so if
          collectionName = ''ab-23-c4'' then storageaccounname = ''ab23c4'''
      elements:
        title: " "
        type: array
        format: tabs
        minItems: 1
        items:
          headerTemplate: "{{ self.name }}"
          type: object
          format: grid
          required:
          - name
          properties:
            name:
              type: string
              title: Storageaccount name prefix
              description: 'Must be lowercase alphanum no-dashes max18char.</br>OK:  ''goodstorage2023''</br>NOK:
                ''bad-STA_with-UPCASE_dashes-and_tooLoong'
              pattern: "^[a-z0-9]{1,18}$"
              options:
                xtra_Immutable: true
  keyvaults:
    title: Keyvaults
    type: object
    properties:
      info:
        type: info
        description: 'Azure keyvaults safely store secret, keys and certificates.
          </br>The first keyvault is special: must always exist and have name keyvaultname
          = collectionname (so if collectionName = ''ab-23-c4'' then keyvaultname
          = ''ab-23-c4'''
      elements:
        title: " "
        type: array
        format: tabs
        minItems: 1
        items:
          headerTemplate: "{{ self.name }}"
          type: object
          format: grid
          required:
          - name
          properties:
            name:
              type: string
              title: Keyvault name prefix
              description: 'Must be lowercase alphanum no-dashes max18char.</br>OK:  ''goodstorage2023''</br>NOK:
                ''bad-STA_with-UPCASE_dashes-and_tooLoong'
              pattern: "^[a-z0-9]{1,18}$"
              options:
                xtra_Immutable: true
