Catalog_title_and_description_in_markdown: |-
    Select products
    --------------------
    See further [documentation in our corporate wiki, in dedicated page detailing these products](https://my.internal.wiki.corp/vendingmaxine/catalog-default) 


Catalog_products:

  "additional_members_of_AADGroup_DataClients":
    Product_title_and_description_in_markdown: |-
        AAD-Group 'mycollection_DataClients' members
        --------------------
        The **mycollection_DataClients** AAD-Group members can access data from resources:
        
        - blob/files
        - storage accounts
        - secrets from keyvaults
        - etc

    Product_item:
      _type: object
      _title_and_description_in_markdown: "{{ self.alias }}"
      _format: grid           #[opt] grid, prefer when content is small and fits well in same row      
      "alias":
        _type: string
        _title_and_description_in_markdown: |-
            Internal alias
            --------------------
            An internal alias to remember what this object_id corresponds to
 
        _pattern: '^[0-9a-z- ]+$'
        _default: "Exs: 'group TeamWhisky' or 'user Siegi' or 'spn cicdWhisky1'"

